package utils

import (
	"log"
	"math"
	"regexp"
	"strconv"
	"strings"
	"time"

	"kweeuhree.receipt-processor-challenge/internal/models"
)

type Utils struct {
	ErrorLog     *log.Logger
	InfoLog      *log.Logger
	ReceiptStore *models.ReceiptStore
}

func NewUtils(errorLog *log.Logger, infoLog *log.Logger, receiptStore *models.ReceiptStore) *Utils {
	return &Utils{
		ErrorLog:     errorLog,
		InfoLog:      infoLog,
		ReceiptStore: receiptStore,
	}
}

func (u *Utils) CalculatePoints(id string) (int, error) {
	u.InfoLog.Printf("Calculating points for receipt with id: %s", id)

	// Get receipt by its id
	receipt, err := u.ReceiptStore.Get(id)
	if err != nil {
		return 0, err
	}

	// Convert receipt's total to a float
	floatTotal, err := strconv.ParseFloat(receipt.Total, 64)
	if err != nil {
		return 0, err
	}

	// Get all points of the receipt
	points := []int{
		u.getRetailerNamePoints(receipt.Retailer),
		u.getRoundTotalPoints(floatTotal),
		u.getQuartersPoints(floatTotal),
		u.getEveryTwoItemsPoints(receipt.Items),
		u.getItemDescriptionPoints(receipt.Items),
		u.getLlmGeneratedPoints(floatTotal),
		u.getOddDayPoints(receipt.PurchaseDate),
		u.getPurchaseTimePoints(receipt.PurchaseTime),
	}

	// Calculate total points of the receipt
	var total int
	for _, point := range points {
		total += point
	}

	u.InfoLog.Printf("Total Points: %d", total)

	return total, nil
}

// Assigns one point for every alphanumeric character in the retailer name
func (u *Utils) getRetailerNamePoints(retailerName string) int {
	points := 0

	// Split the retailers name
	splitChars := strings.Split(retailerName, "")

	// For each character is splitChars, check if the character is alphanumeric
	for _, char := range splitChars {
		if u.isAlphanumeric(char) {
			points += 1
		}
	}

	return points
}

// Checks if the character is alphanumeric
func (u *Utils) isAlphanumeric(char string) bool {
	return regexp.MustCompile(`^[a-zA-Z0-9]+$`).MatchString(char)
}

// Assigns 50 points if the total is a round dollar amount with no cents
func (u *Utils) getRoundTotalPoints(total float64) int {
	points := 0

	// Use modulo operator to determine points
	if math.Mod(total, 1.00) == 0 {
		points = 50
	}

	return points
}

// Assigns 25 points if the total is a multiple of `0.25`
func (u *Utils) getQuartersPoints(total float64) int {
	points := 0

	// Use modulo operator to determine points
	if math.Mod(total, 0.25) == 0 {
		points = 25
	}

	return points
}

// Assigns 5 points for every two items on the receipt
func (u *Utils) getEveryTwoItemsPoints(items []models.Item) int {
	points := 0

	// Get length of items and determine pairs
	len := len(items)
	pairs := (len - (len % 2)) / 2

	if pairs > 0 {
		points = pairs * 5
	}

	return points
}

// Assigns points based on item description
func (u *Utils) getItemDescriptionPoints(items []models.Item) int {
	// If the trimmed length of the item description is a multiple of 3,
	// multiply the price by `0.2` and round up to the nearest integer.
	// The result is the number of points earned.
	points := 0

	// Loop through items
	for _, item := range items {
		// Per each item, trim and get the length
		trimmedDesc := strings.TrimSpace(item.ShortDescription)
		trimmedLen := len(trimmedDesc)

		// Use modulo operator to determine points
		if trimmedLen%3 == 0 {
			parsedPrice, err := strconv.ParseFloat(item.Price, 64)

			if err != nil {
				u.ErrorLog.Printf("Error parsing price for item %s: %v", item.ShortDescription, err)
				return 0
			}
			// Round up
			itemPoints := math.Ceil(parsedPrice * 0.2)
			points += int(itemPoints)
		}
	}

	return points
}

// Assigns points if the program is generated by an LLM
func (u *Utils) getLlmGeneratedPoints(total float64) int {
	// If and only if this program is generated using a large language model,
	// 5 points if the total is greater than 10.00.
	points := 0

	isGeneratedByLlm := false

	if isGeneratedByLlm && total > 10 {
		points = 5
	}

	return points
}

// Assigns 6 points if the day in the purchase date is odd
func (u *Utils) getOddDayPoints(purchaseDate string) int {
	points := 0

	// Determine the layout for time parsing
	layout := "2006-01-02"
	date, err := time.Parse(layout, purchaseDate)
	if err != nil {
		u.ErrorLog.Print("Error parsing date:", err)
		return 0

	}
	// Get day of purchase
	day := date.Day()

	// Use modulo operator to determine points
	if day%2 == 1 {
		points = 6
	}

	return points
}

// Assigns 10 points if the time of purchase is after 2:00pm and before 4:00pm
func (u *Utils) getPurchaseTimePoints(purchaseTime string) int {
	points := 0
	// Determine the layout for time parsing
	layout := "15:04"
	parsedTime, err := time.Parse(layout, purchaseTime)
	if err != nil {
		u.ErrorLog.Print("Error parsing time:", err)
		return 0
	}
	// Define starting end ending time for extra bonus
	bonusStart, _ := time.Parse(layout, "14:00") // 2:00pm
	bonusEnd, _ := time.Parse(layout, "16:00")   // 4:00pm

	// Determine whether the puchase was made during the bonus window
	if parsedTime.After(bonusStart) && parsedTime.Before(bonusEnd) {
		points = 10
	}

	return points
}
